//Common actions
export const RECOVER_DATA_FROM_LOCAL_STORAGE = 'RECOVER_DATA_FROM_LOCAL_STORAGE';

//Description
export const HANDLE_DESCRIPTION = 'HANDLE_DESCRIPTION';
export const HANDLE_ESTIMATEDTIME = 'HANDLE_ESTIMATEDTIME';
export const HANDLE_STEP_ONE = 'HANDLE_STEP_ONE';

//Category
export const HANDLE_CATEGORY = 'HANDLE_CATEGORY';
export const HANDLE_SUBCATEGORY = 'HANDLE_SUBCATEGORY';
export const HANDLE_PRICE = 'HANDLE_PRICE';
export const HANDLE_STEP_TWO = 'HANDLE_STEP_TWO';

//Contact
export const HANDLE_NAME = 'HANDLE_NAME';
export const HANDLE_EMAIL = 'HANDLE_EMAIL';
export const HANDLE_PHONE = 'HANDLE_PHONE';
export const HANDLE_STEP_THREE = 'HANDLE_STEP_THREE';

//Details
export const CONFIRM_BUDGET = 'CONFIRM_BUDGET';

//async

//Category
export const FETCH_SUBCATEGORIES = 'FETCH_SUBCATEGORIES';
export const FETCH_CATEGORIES_INIT = 'FETCH_CATEGORIES_INIT';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_SUBCATEGORIES_INIT = 'FETCH_SUBCATEGORIES_INIT';
export const FETCH_SUBCATEGORIES_SUCCESS = 'FETCH_SUBCATEGORIES_SUCCESS';
export const FETCH_SUBCATEGORIES_FAILURE = 'FETCH_SUBCATEGORIES_FAILURE';

//Contact
export const CHECK_MAIL_INIT = 'CHECK_MAIL_INIT';
export const CHECK_MAIL_SUCCESS = 'CHECK_MAIL_SUCCESS';
export const CHECK_MAIL_FAILURE = 'CHECK_MAIL_FAILURE';
